apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::066499543631:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1VBZEP1BL73DA
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::066499543631:role/UdacityFlaskDeployCBKubectlRole
      username: cj-discover-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-25T14:48:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "10714"
  uid: 47e79053-b1ee-4f12-a818-5a88e3bba464
